# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: 
title: Xiaozhong's Blog
description: > #this means to ignore newlines until "nav_lists:"
  Xiaozhong's Blog

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

# paths:
#   home: /
#   all:  /all.html
#   rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
github: [metadata]
# repository:  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai

## Author & social ##
author:
  name: Someone
  email:      xiaozhong.liu@outlook.com
  # facebook: #your Facebook username
  # twitter:  #your Twitter username
  github:     xiaozhongliu
  juejin:     587ae9c95c497d00589f5407
  # googleplus: #your Google+ username
  # weibo:    #your Weibo username
  # douban:   #your Douban username
  linkedin:   xiaozhong-liu

## Comment system (Disqus) ##
disqus:
  shortname:  xiaozhongliu

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - jekyll-text-theme.gemspec
  - /node_modules
  - /test

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false